/*
  Sourced these from some website that is no longer up. If you can source these let me know and I will give credit.
*/


var sillyQuestions = [
    "What breed of dog would you be?",
    "What was the worst haircut you ever had?",
    "If you were a wrestler what would be your entrance theme song?",
    "What would be your professional wrestling name? What would be your finishing move?",
    "What food do you love that a lot of people might find a little odd?",
    "What food does everyone love but you hate?",
    "What was the worst style choice you ever made?",
    "Would you rather be the funniest or smartest person in the room? Why?",
    "You have your own late-night talk show, who do you invite as your first guest?",
    "What’s your best “my coworkers are crazy” story?",
    "What’s the best or worst prank you’ve played on someone?",
    "What’s the best or worst prank you’ve played on you?",
    "What was your least favorite food as a child? Do you still hate it or do you love it now?",
    "If you could hang out with any cartoon character, who would you choose and why?",
    "What’s the silliest thing you are pretty good at?",
    "What’s the worst advice you’ve been given?",
    "What are some of the dumbest misadventures you’ve been on?",
    "If you had to eat one meal every day for the rest of your life what would it be?",
    "What’s the weirdest food you’ve eaten?",
    "What is something you eat that other people would find gross?",
    "What is the weirdest food combination you’ve made and tried?",
    "What’s the best cake you’ve ever eaten?",
    "What recent trend are you totally on board with?",
    "What fruit or vegetable would you most want to be?",
    "Describe yourself in terms of food.",
    "What food is underrated or underappreciated?",
    "What movie is underrated or underappreciated?",
    "Does your current car have a name? What is it?",
    "If you could choose any two famous people to have dinner with who would they be?",
    "What is the most unique or silliest problem you have going on in your life at the moment?",
    "If you could choose any person from history to be your imaginary friend, who would it be and why?",
    "What songs would be played on a loop in hell?",
    "What was your funniest or worst experience with a dentist?",
    "Who is the funniest person in your family?",
    "What useless facts do you know?",
    "What weird thing do you have nostalgia for?",
    "What’s your favorite way to waste time online?",
    "Do you think horoscopes are accurate?",
    "What fictional world or place would you like to visit?",
    "Have you ever been told you look like someone famous, who was it?",
    "What are you kind of snobby about?",
    "If you could be on a reality TV show, which one would you choose and why?",
    "Which are cooler: dinosaurs or dragons/",
    "What was the worst job you ever had?",
    "What hobby would you be a lot of fun to get into?",
    "If someone came up to you and said “Hey, do that thing you do!”, what thing would pop into your head first?",
    "How could carousels be spiced up so they are more exciting?",
    "What slang are you really happy went out of fashion?",
    "If you could bring back any fashion trend what would it be?",
    "You can have anyone fictional as your imaginary friend, who do you choose and why?",
    "If you could rename yourself, what name would you pick?",
    "If aliens landed on earth tomorrow and offered to take you home with them, would you go?",
    "What are some of your guilty pleasures?",
    "Would you go with aliens if they beamed down to Earth?",
    "What was the funniest thing you’ve seen recently online?",
    "What was the craziest theme park or fair ride you’ve been on?",
    "If a new volcano formed and the government had an online contest to see what it would be named, what name would you submit?",
    "What historical period would be the best to be born in?",
    "What toy did you hate most as a child?",
    "How do you describe millenials or Gen Z?",
    "If the universe is just a simulation, what update or patch does it need?",
    "What is one article of clothing that someone could wear that would make you walk out on a date with them?",
    "80s, 90s, 00s, 10s: Which decade do you love the most and why?",
    "You have to sing karaoke, what song do you pick?",
    "If you could be any supernatural creature, what would you be and why?",
    "What’s the weirdest way you have met someone?",
    "What is your favorite magical or mythological animal?",
    "What’s your favorite line from a book or a movie?",
    "What assumption you made went hilariously wrong?",
    "What card or board games do you like to play?",
    "If you were left on a deserted island with either your worst enemy or no one, which would you choose? Why?",
    "Who was your childhood actor/actress crush?",
    "Who is your favorite Disney hero or heroine? Would you trade places with them?",
    "The zombie apocalypse is coming, who are 3 people you want on your team?",
    "If a movie was made of your life what genre would it be, who would play you?",
    "If you were famous, what would you be famous for?",
    "What is the best-backhanded compliment you’ve heard / can think of on the spot?",
    "What catchy jingle or a bit of advertising has stuck with you all these years?",
    "What’s the most outdated piece of tech you still use regularly?",
    "What weird quirks did you pick up from your parents?",
    "What is the most clever or funniest use of advertising you’ve seen?",
    "If you could choose your dreams, what would you prefer to dream about?",
    "How do you feel about clowns?",
    "What fictional family would you be a member of?",
    "Which words or phrases do you overuse?",
    "Do you think ignorance is bliss?",
    "What's the best pickup line you ever heard?",
    "A toy company makes an action figure of you. What accessories does it come with?",
    "Who's voice would you like to narrate your life inside your head?",
    "What is a mundane daily task that you are world class at?",
    "If you were arrested what would your friends/family assume it was for?"
    ];
